/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SaisenScore {
  export type PlayerStatsStruct = {
    totalScore: BigNumberish;
    wins: BigNumberish;
    losses: BigNumberish;
    rating: BigNumberish;
    totalMatches: BigNumberish;
    lastSubmission: BigNumberish;
  };

  export type PlayerStatsStructOutput = [
    totalScore: bigint,
    wins: bigint,
    losses: bigint,
    rating: bigint,
    totalMatches: bigint,
    lastSubmission: bigint
  ] & {
    totalScore: bigint;
    wins: bigint;
    losses: bigint;
    rating: bigint;
    totalMatches: bigint;
    lastSubmission: bigint;
  };
}

export interface SaisenScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_RATING"
      | "LOSS_ELO"
      | "MAX_SCORE"
      | "MIN_DURATION_SECS"
      | "SUBMIT_COOLDOWN"
      | "WIN_ELO"
      | "getBatchStats"
      | "getPlayerStats"
      | "getRegisteredCount"
      | "players"
      | "registeredPlayers"
      | "submitScore"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ScoreSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LOSS_ELO", values?: undefined): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_DURATION_SECS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBMIT_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WIN_ELO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBatchStats",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_RATING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LOSS_ELO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DURATION_SECS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBMIT_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WIN_ELO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBatchStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registeredPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    player: AddressLike,
    score: BigNumberish,
    win: boolean,
    newRating: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    score: bigint,
    win: boolean,
    newRating: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    score: bigint;
    win: boolean;
    newRating: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SaisenScore extends BaseContract {
  connect(runner?: ContractRunner | null): SaisenScore;
  waitForDeployment(): Promise<this>;

  interface: SaisenScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_RATING: TypedContractMethod<[], [bigint], "view">;

  LOSS_ELO: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_DURATION_SECS: TypedContractMethod<[], [bigint], "view">;

  SUBMIT_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  WIN_ELO: TypedContractMethod<[], [bigint], "view">;

  getBatchStats: TypedContractMethod<
    [addrs: AddressLike[]],
    [SaisenScore.PlayerStatsStructOutput[]],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [SaisenScore.PlayerStatsStructOutput],
    "view"
  >;

  getRegisteredCount: TypedContractMethod<[], [bigint], "view">;

  players: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        wins: bigint;
        losses: bigint;
        rating: bigint;
        totalMatches: bigint;
        lastSubmission: bigint;
      }
    ],
    "view"
  >;

  registeredPlayers: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  submitScore: TypedContractMethod<
    [score: BigNumberish, win: boolean, matchDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOSS_ELO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DURATION_SECS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUBMIT_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WIN_ELO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatchStats"
  ): TypedContractMethod<
    [addrs: AddressLike[]],
    [SaisenScore.PlayerStatsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [SaisenScore.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        wins: bigint;
        losses: bigint;
        rating: bigint;
        totalMatches: bigint;
        lastSubmission: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registeredPlayers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [score: BigNumberish, win: boolean, matchDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;

  filters: {
    "ScoreSubmitted(address,uint256,bool,uint256,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
  };
}
